#!/usr/bin/env python3
"""Write docker compose env file from config/omeka-test/settings.yaml (single source of truth)."""
from __future__ import annotations

import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    print("PyYAML required: pip install pyyaml", file=sys.stderr)
    sys.exit(1)

ROOT = Path(__file__).resolve().parents[2]
SETTINGS = ROOT / "config" / "omeka-test" / "settings.yaml"
SETTINGS_LOCAL = ROOT / "config" / "omeka-test" / "settings.local.yaml"
OUT = ROOT / "config" / "omeka-test" / "generated.env"
LOCAL_CONFIG = ROOT / "config" / "omeka-test" / "local.config.php"

LOCAL_CONFIG_TEMPLATE = """<?php
/**
 * Omeka S local overrides (generated by scripts/sync-docker-config.py).
 */
return [
    'session' => [
        'config' => [
            'cookie_samesite' => 'Lax',
        ],
    ],
];
"""


def deep_merge(base: dict, overlay: dict) -> dict:
    out = dict(base)
    for key, val in overlay.items():
        if isinstance(val, dict) and isinstance(out.get(key), dict):
            out[key] = deep_merge(out[key], val)
        else:
            out[key] = val
    return out


def load_settings() -> dict:
    if not SETTINGS.is_file():
        print(
            f"Missing {SETTINGS.relative_to(ROOT)} — run ./scripts/ensure-local-config.sh",
            file=sys.stderr,
        )
        sys.exit(1)
    data = yaml.safe_load(SETTINGS.read_text()) or {}
    if SETTINGS_LOCAL.is_file():
        local = yaml.safe_load(SETTINGS_LOCAL.read_text()) or {}
        data = deep_merge(data, local)
    return data


def main() -> None:
    data = load_settings()
    db = data["database"]
    omeka = data["omeka"]
    lines = [
        f"MARIADB_DATABASE={db['name']}",
        f"MARIADB_USER={db['user']}",
        f"MARIADB_PASSWORD={db['password']}",
        f"MARIADB_ROOT_PASSWORD={db['root_password']}",
        f"OMEKA_ADMIN_EMAIL={omeka['admin_email']}",
        f"OMEKA_ADMIN_NAME={omeka['admin_name']}",
        f"OMEKA_ADMIN_PASSWORD={omeka['admin_password']}",
        f"OMEKA_SITE_TITLE={omeka['site_title']}",
        f"DB_HOST={db['host']}",
        f"DB_NAME={db['name']}",
        f"DB_USER={db['user']}",
        f"DB_PASSWORD={db['password']}",
    ]
    OUT.write_text("\n".join(lines) + "\n")
    LOCAL_CONFIG.write_text(LOCAL_CONFIG_TEMPLATE)
    print(f"Wrote {OUT}")
    print(f"Wrote {LOCAL_CONFIG}")
    public_url = omeka.get("public_url")
    if public_url:
        print(f"Browser URL (use consistently): {public_url.rstrip('/')}/admin")


if __name__ == "__main__":
    main()
